services:
  audiologger:
    image: ghcr.io/oszuidwest/zwfm-audiologger:latest
    container_name: audiologger
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - audiologger-data:/var/audio
      - ./streams.json:/app/streams.json:ro
      - audiologger-logs:/var/log
    environment:
      - CONFIG_FILE=/app/streams.json
      - TZ=Europe/Amsterdam

volumes:
  audiologger-data:
    driver: local
  audiologger-logs:
    driver: local