services:
  audiologger:
    image: ghcr.io/oszuidwest/zwfm-audiologger:latest
    container_name: audiologger
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - audiologger-data:/var/audio
      - ./config.json:/app/config.json:ro
      - audiologger-logs:/var/log
    environment:
      - TZ=Europe/Amsterdam
    command: ["./audiologger", "-config", "/app/config.json"]

volumes:
  audiologger-data:
    driver: local
  audiologger-logs:
    driver: local